{% set name = "fetch" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gruntwork-io/fetch/archive/v{{ version }}.tar.gz
  sha256: 81086290cc82a990a7369c710179869e3d1a5b3fea60df5997138a96688e9899

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - fetch --help

about:
  home: https://github.com/gruntwork-io/fetch
  license: MIT
  license_file:
    - LICENSE.txt
    - license-files/
  summary: Download assets from a commit, branch, or tag of GitHub repositories
  dev_url: https://github.com/gruntwork-io/fetch

extra:
  recipe-maintainers:
    - danielnachun
