schema_version: 1

context:
  version: "0.4.8"

package:
  name: fetch
  version: ${{ version }}

source:
  url: https://github.com/gruntwork-io/fetch/archive/v${{ version }}.tar.gz
  sha256: 8192dddb375e2a8765e54e27c65b544068b35bd349f9ad669d6269734f3b5f76

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - fetch --help

about:
  license: MIT
  license_file:
    - LICENSE.txt
    - license-files/
  summary: Download assets from a commit, branch, or tag of GitHub repositories
  homepage: https://github.com/gruntwork-io/fetch
  repository: https://github.com/gruntwork-io/fetch

extra:
  recipe-maintainers:
    - danielnachun
